name: hymn_app
description: A Christian hymn app with audio and themes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  just_audio: ^0.9.36
  google_fonts: ^6.2.1
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/hymns_all.json